image: python:3.6

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# NOTE: Pip's cache doesn't store the python packages. This is probably OK.
cache:
  paths:
    - .cache/pip

before_script:
- export PATH=$PATH:$PYTHONUSERBASE/bin
- python -V
# Update VERSION file with the commit tag
- |
    if [ "$CI_COMMIT_TAG" ]; then
      echo "$CI_COMMIT_TAG" > flywheel_cli/VERSION
    fi
- pip install -q twine
- pip install --upgrade -e .[dev]

test:
  script:
  - pytest tests/unit_tests
  # Informational for now
  - pylint --rcfile .pylintrc flywheel_cli/ || true

run:
  script:
  - python setup.py bdist_wheel
  - twine check dist/*.whl
  - |
      if [ "$CI_COMMIT_TAG" ]; then
        twine upload -u $PYPI_USER -p $PYPI_PASS dist/*.whl
      fi

  artifacts:
    paths:
    - dist/*.whl
