# This file is a template, and might need editing before it works on your project.
# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: python:3.6

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# Instead we use user-site/ as the user base
# See: https://pip.readthedocs.io/en/latest/user_guide/#user-installs
cache:
  paths:
    - .cache/pip
    - .cache/user-site/

before_script:
- mkdir -p .cache/user-site/
- export PYTHONUSERBASE=$(realpath .cache/user-site/)
- export PATH=$PATH:$PYTHONUSERBASE/bin
- python -V
# Update VERSION file with the commit tag
- |
    if [ "$CI_COMMIT_TAG" ]; then
      echo "$CI_COMMIT_TAG" > flywheel_cli/VERSION
    fi
# Install dependencies to the --user site
- pip install -q --user -r test-requirements.txt twine
- pip install -e .

test:
  script:
  - pytest tests/unit_tests

run:
  script:
  - python setup.py bdist_wheel
  - twine check dist/*.whl
  - |
      if [ "$CI_COMMIT_TAG" ]; then
        twine upload -u $PYPI_USER -p $PYPI_PASS dist/*.whl
      fi

  artifacts:
    paths:
    - dist/*.whl
